name: Cross-Platform Examples Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install nheri-simcenter
          python -m pip install GPy==1.13.2

      - name: Run the examples
        run: python run_examples.py

      - name: Check output files
        run: python check_output.py

      - name: Upload output log
        uses: actions/upload-artifact@v3
        with:
          name: output-log-${{ matrix.os }}
          path: run_examples_output.txt

      - name: Upload check output log
        uses: actions/upload-artifact@v3
        with:
          name: check-output-log-${{ matrix.os }}
          path: check_output_log.txt

      - name: Upload cache directory
        uses: actions/upload-artifact@v3
        with:
          name: cache-${{ matrix.os }}
          path: cache