title: Bayesian Model Class Selection for Material Constitutive Models
summary: |
  In this example, model class selection is performed using the Bayesian approach with two candidate model classes - STEEL01 and STEEL02 material model in OpenSees. Experimental data is
  passed in to quoFEM from an external file, and the output is the time-history of
  stress - a non-scalar response quantity.
author:
- family: Bangalore Satish
  given: Aakash
collection-title: Material Model
difficulty: 0
