summary: Custom UQ Example
archive: $SIMCENTER_DEV
archive_location: quoFEM/examples/qfem-0020
author:
- family: Gardner & Yi
  given: Michael & Sangri
collection-title: Custom UQ for UQpy
id: qfem-0020
title: Custon UQ for UQpy
type: book
difficulty: 2
